modLoader="javafml"
loaderVersion="[${loader_version},)"
license="GNU LGPLv3"
issueTrackerURL="https://github.com/Flemmli97/DebugUtils/issues"
[[mixins]]
config = "debugutils.mixins.json"
[[mods]]
modId="debugutils"
version="${version}"
displayName="Debug Utils"
displayURL="${homepage}"
logoFile="icon.png"
authors="Flemmli97"
description='''Enables various debugging tools from mojang'''
[[dependencies.debugutils]]
modId="minecraft"
type="required"
versionRange="[${mcversion},)"
ordering="NONE"
side="BOTH"
